# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github
    - name: Build with Maven
      run: mvn -s settings.xml -B package --file pom.xml -Dkafka-connect-pubsub.version=${{ github.head_ref }}-${{ github.run_number }}
      env:
        AVRO_MESSAGE_BATCH_TOKEN: ${{ secrets.AVRO_MESSAGE_BATCH_TOKEN }}
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s settings.xml -Dkafka-connect-pubsub.version=${{ github.head_ref }}-${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Publish to private artifactory
      shell: bash
      run: mvn deploy -s settings.xml -Dkafka-connect-pubsub.version=${{ github.head_ref }}-${{ github.run_number }} -DaltDeploymentRepository=artifactory::default::$ARTIFACTORY_CANDIDATES_URL
      env:
        ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        ARTIFACTORY_CANDIDATES_URL: ${{ secrets.ARTIFACTORY_CANDIDATES_URL }}

